#!/bin/bash

export DOTFILES_DIR="$HOME/.dotfiles"

export LOCAL_BIN="$HOME/.local/bin"
export BACKUPS_DIR="$HOME/backups"
export NOTES_DIR="$HOME/notes"

# Put this somewhere you can store large files
export TMP_DIR="$HOME/tmp"

# Some programs need this to store large files (e.g. vscode)
export XDG_RUNTIME_DIR="$HOME/xdg"
export XDG_CONFIG_HOME="$HOME/.config"

export ZSH="$HOME/.oh-my-zsh"
