#!/bin/bash

export DOTFILES_DIR="$HOME/dotfiles"

export LOCAL_BIN="$HOME/.local/bin"
export BACKUPS_DIR="$HOME/backups"
export NOTES_DIR="$HOME/notes"

# Put this somewhere you can store large files
export TMP_DIR="$HOME/tmp"

# Some programs need this to store large files (e.g. vscode)
export XDG_RUNTIME_DIR="$HOME/xdg"
export XDG_CONFIG_HOME="$HOME/.config"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export ZSH="$HOME/.oh-my-zsh"
